# Generated by Django 4.2.4 on 2023-10-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videourl',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
