# Generated by Django 4.2.4 on 2023-10-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_videourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videourl',
        ),
    ]
